language: node_js

os:
  - linux
  - osx
  - windows

# https://github.com/nodejs/Release#nodejs-release-working-group
node_js:
  - 10
  - 12
  - 14

install:
- ./travis/install.sh

script:
  - npm run lint
  - npm test

notifications:
  email: false
